#!/usr/bin/env python3
"""
Generate font_15x21_ank.h from fontk_8x8.h using Scale3x algorithm.

Source:  lib/st7789/fontk_8x8.h — column-major, 8 bytes/glyph, bit0=top row
         5 columns used, 7 rows used

Output:  lib/st7789/font_15x21_ank.h — row-major, 2 bytes/row, 21 rows/glyph
         Cell 15x21 (active area = full cell, no margin)
         byte0: cols 0-7  (bit7=col0, bit0=col7)
         byte1: cols 8-14 (bit7=col8, bit1=col14, bit0 unused)
"""

import re
import sys
import os

SRC_W = 5
SRC_H = 7
DST_W = 15   # SRC_W * 3
DST_H = 21   # SRC_H * 3
GLYPH_COUNT = 256
ROW_BYTES = 2


def parse_fontk_8x8(path):
    with open(path, 'r') as f:
        text = f.read()
    hex_vals = re.findall(r'0x([0-9A-Fa-f]{2}),', text)
    vals = [int(h, 16) for h in hex_vals]
    if len(vals) < GLYPH_COUNT * 8:
        raise ValueError(f"Expected {GLYPH_COUNT * 8} bytes, got {len(vals)}")
    return [vals[i * 8:(i + 1) * 8] for i in range(GLYPH_COUNT)]


def glyph_to_grid(glyph_bytes):
    grid = [[0] * SRC_W for _ in range(SRC_H)]
    for x in range(SRC_W):
        for y in range(SRC_H):
            grid[y][x] = (glyph_bytes[x] >> y) & 1
    return grid


def P(src, x, y):
    return src[y][x] if 0 <= x < SRC_W and 0 <= y < SRC_H else 0


def scale3x(src):
    """Scale3x algorithm: 5x7 -> 15x21."""
    dst = [[0] * DST_W for _ in range(DST_H)]
    for sy in range(SRC_H):
        for sx in range(SRC_W):
            A=P(src,sx-1,sy-1); B=P(src,sx,sy-1); C=P(src,sx+1,sy-1)
            D=P(src,sx-1,sy  ); E=P(src,sx,sy  ); F=P(src,sx+1,sy  )
            G=P(src,sx-1,sy+1); H=P(src,sx,sy+1); I=P(src,sx+1,sy+1)

            e0 = D if (D==B and D!=H and B!=F) else E
            e2 = F if (B==F and B!=D and F!=H) else E
            e6 = D if (D==H and D!=B and H!=F) else E
            e8 = F if (H==F and D!=H and B!=F) else E
            e1 = B if ((D==B and D!=H and B!=F and E!=C) or (B==F and B!=D and F!=H and E!=A)) else E
            e3 = D if ((D==B and D!=H and B!=F and E!=G) or (D==H and D!=B and H!=F and E!=A)) else E
            e5 = F if ((B==F and B!=D and F!=H and E!=I) or (H==F and D!=H and B!=F and E!=C)) else E
            e7 = H if ((H==F and D!=H and B!=F and E!=G) or (D==H and D!=B and H!=F and E!=I)) else E
            e4 = E

            dx, dy = sx * 3, sy * 3
            dst[dy  ][dx]=e0; dst[dy  ][dx+1]=e1; dst[dy  ][dx+2]=e2
            dst[dy+1][dx]=e3; dst[dy+1][dx+1]=e4; dst[dy+1][dx+2]=e5
            dst[dy+2][dx]=e6; dst[dy+2][dx+1]=e7; dst[dy+2][dx+2]=e8
    return dst


def grid_to_bytes(dst):
    """Pack 15x21 pixel grid into row-major 2-bytes/row."""
    rows = []
    for row in dst:
        b0, b1 = 0, 0
        for col in range(DST_W):
            if row[col]:
                if col < 8:
                    b0 |= (1 << (7 - col))
                else:
                    b1 |= (1 << (7 - (col - 8)))
        rows.append((b0, b1))
    return rows


def visualise(grid, w, h):
    return '\n'.join(''.join('X' if grid[y][x] else '.' for x in range(w)) for y in range(h))


def generate_header(glyphs, out_path):
    lines = [
        '#pragma once',
        '',
        '#include <stdint.h>',
        '',
        '// 15x21 ANK bitmap font for ST7789.',
        '// Generated by tools/gen_font_15x21.py from fontk_8x8.h using Scale3x.',
        '//',
        '// Cell: 15x21px  (no margin, advance gap handled by cursor)',
        '// Format: row-major, 2 bytes/row',
        '//   byte0: cols 0-7  (bit7=col0, bit0=col7)',
        '//   byte1: cols 8-14 (bit7=col8, bit1=col14, bit0 unused)',
        '',
        '#define FONT15X21_ANK_WIDTH       15',
        '#define FONT15X21_ANK_HEIGHT      21',
        '#define FONT15X21_ANK_ROW_BYTES    2',
        '#define FONT15X21_ANK_GLYPH_BYTES (FONT15X21_ANK_HEIGHT * FONT15X21_ANK_ROW_BYTES)',
        '#define FONT15X21_ANK_GLYPH_COUNT 256',
        '',
        'static const uint8_t font15x21_ank[FONT15X21_ANK_GLYPH_COUNT][FONT15X21_ANK_GLYPH_BYTES] = {',
    ]

    for code, glyph_bytes in enumerate(glyphs):
        src = glyph_to_grid(glyph_bytes)
        dst = scale3x(src)
        cell_rows = grid_to_bytes(dst)
        lines.append(f'  /* Code:0x{code:02X} */ {{')
        for b0, b1 in cell_rows:
            lines.append(f'    0x{b0:02X}, 0x{b1:02X},')
        lines.append('  },')

    lines.append('};')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Written: {out_path}  ({len(glyphs)*DST_H*ROW_BYTES} bytes)")


def debug_preview(glyphs, codes):
    for code in codes:
        src = glyph_to_grid(glyphs[code])
        dst = scale3x(src)
        label = chr(code) if 0x20 <= code <= 0x7E else '?'
        print(f"\n--- 0x{code:02X} '{label}' ---")
        print("src 5x7:"); print(visualise(src, SRC_W, SRC_H))
        print("Scale3x 15x21:"); print(visualise(dst, DST_W, DST_H))


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_dir = os.path.dirname(script_dir)
    src_path = os.path.join(repo_dir, 'lib', 'st7789', 'fontk_8x8.h')
    out_path = os.path.join(repo_dir, 'lib', 'st7789', 'font_15x21_ank.h')

    if not os.path.exists(src_path):
        print(f"Error: {src_path} not found", file=sys.stderr)
        sys.exit(1)

    print(f"Reading: {src_path}")
    glyphs = parse_fontk_8x8(src_path)
    print(f"Parsed {len(glyphs)} glyphs")

    debug_preview(glyphs, [0x41, 0x30, 0xB1])
    generate_header(glyphs, out_path)
    print("Done.")


if __name__ == '__main__':
    main()
