#!/usr/bin/env python3
"""
Generate font_12x16_ank.h from fontk_8x8.h using Scale2x algorithm.

Source:  fontk_8x8.h  — column-major, 8 bytes/glyph, bit0=top row
         5 columns used (FONT_WIDTH=5), 7 rows used (FONT_HEIGHT=7)

Output:  font_12x16_ank.h — row-major, 2 bytes/row, 16 rows/glyph
         Cell 12x16, active area 10x14 (1px margin each side)
         byte0: cols 0-7  (bit7=col0, LSB=col7)
         byte1: cols 8-11 (bit7=col8, bit4=col11, bits3-0 unused)

Scale2x (EPX) smooths diagonal pixel-art lines on exact 2x upscale.
"""

import re
import sys
import os

SRC_W = 5
SRC_H = 7
DST_W = 10   # SRC_W * 2
DST_H = 14   # SRC_H * 2
CELL_W = 12
CELL_H = 16
MARGIN_X = 1
MARGIN_Y = 1
GLYPH_COUNT = 256


def parse_fontk_8x8(path):
    """Parse fontk_8x8.h -> list of 256 glyphs, each a list of 8 bytes."""
    with open(path, 'r') as f:
        text = f.read()
    # Extract only data bytes (followed by comma) — skip /* Code:0xNN */ comments
    hex_vals = re.findall(r'0x([0-9A-Fa-f]{2}),', text)
    vals = [int(h, 16) for h in hex_vals]
    if len(vals) < GLYPH_COUNT * 8:
        raise ValueError(f"Expected {GLYPH_COUNT * 8} bytes, got {len(vals)}")
    glyphs = []
    for i in range(GLYPH_COUNT):
        glyphs.append(vals[i * 8:(i + 1) * 8])
    return glyphs


def glyph_to_grid(glyph_bytes):
    """Convert 8-byte column-major glyph to 5x7 pixel grid.
    Returns grid[y][x] where y=0 is top, x=0 is left.
    """
    grid = [[0] * SRC_W for _ in range(SRC_H)]
    for x in range(SRC_W):
        col_byte = glyph_bytes[x]
        for y in range(SRC_H):
            grid[y][x] = (col_byte >> y) & 1
    return grid


def scale2x(src):
    """Apply Scale2x (EPX) algorithm: 5x7 -> 10x14.
    Returns dst[y][x] for y in 0..13, x in 0..9.
    """
    dst = [[0] * DST_W for _ in range(DST_H)]

    def P(x, y):
        """Source pixel with out-of-bounds clamped to 0."""
        if 0 <= x < SRC_W and 0 <= y < SRC_H:
            return src[y][x]
        return 0

    for sy in range(SRC_H):
        for sx in range(SRC_W):
            E = P(sx, sy)
            B = P(sx,     sy - 1)  # above
            D = P(sx - 1, sy)      # left
            F = P(sx + 1, sy)      # right
            H = P(sx,     sy + 1)  # below

            if B != H and D != F:
                e0 = D if D == B else E  # top-left
                e1 = F if B == F else E  # top-right
                e2 = D if D == H else E  # bottom-left
                e3 = F if H == F else E  # bottom-right
            else:
                e0 = e1 = e2 = e3 = E

            dx, dy = sx * 2, sy * 2
            dst[dy    ][dx    ] = e0
            dst[dy    ][dx + 1] = e1
            dst[dy + 1][dx    ] = e2
            dst[dy + 1][dx + 1] = e3

    return dst


def active_to_cell_bytes(active):
    """Pack 10x14 active pixel grid into 12x16 cell as list of (byte0, byte1) per row."""
    rows = []
    for cy in range(CELL_H):
        byte0 = 0
        byte1 = 0
        ay = cy - MARGIN_Y
        if 0 <= ay < DST_H:
            for ax in range(DST_W):
                cx = ax + MARGIN_X
                if active[ay][ax]:
                    if cx < 8:
                        byte0 |= (1 << (7 - cx))
                    else:
                        byte1 |= (1 << (7 - (cx - 8)))
        rows.append((byte0, byte1))
    return rows


def visualise(grid, width, height):
    """Return ASCII art of a pixel grid for debugging."""
    lines = []
    for y in range(height):
        lines.append(''.join('X' if grid[y][x] else '.' for x in range(width)))
    return '\n'.join(lines)


def generate_header(glyphs, out_path):
    lines = []
    lines.append('#pragma once')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append('// 12x16 ANK bitmap font for ST7735/ST7789.')
    lines.append('// Generated by tools/gen_font_12x16.py from fontk_8x8.h using Scale2x.')
    lines.append('// Scale2x smooths diagonal lines compared to simple 2x pixel replication.')
    lines.append('//')
    lines.append('// Cell: 12x16px  Active area: 10x14px  Margin: 1px each side')
    lines.append('// Format: row-major, 2 bytes/row')
    lines.append('//   byte0: cols 0-7  (bit7=col0, bit0=col7)')
    lines.append('//   byte1: cols 8-11 (bit7=col8, bit4=col11, bits3-0 unused)')
    lines.append('')
    lines.append('#define FONT12X16_ANK_WIDTH       12')
    lines.append('#define FONT12X16_ANK_HEIGHT      16')
    lines.append('#define FONT12X16_ANK_ROW_BYTES    2')
    lines.append('#define FONT12X16_ANK_GLYPH_BYTES (FONT12X16_ANK_HEIGHT * FONT12X16_ANK_ROW_BYTES)')
    lines.append('#define FONT12X16_ANK_GLYPH_COUNT 256')
    lines.append('#define FONT12X16_ANK_ACTIVE_WIDTH  10')
    lines.append('#define FONT12X16_ANK_ACTIVE_HEIGHT 14')
    lines.append('#define FONT12X16_ANK_MARGIN_X       1')
    lines.append('#define FONT12X16_ANK_MARGIN_Y       1')
    lines.append('')
    lines.append('static const uint8_t font12x16_ank[FONT12X16_ANK_GLYPH_COUNT][FONT12X16_ANK_GLYPH_BYTES] = {')

    for code, glyph_bytes in enumerate(glyphs):
        src_grid = glyph_to_grid(glyph_bytes)
        dst_grid = scale2x(src_grid)
        cell_rows = active_to_cell_bytes(dst_grid)

        lines.append(f'  /* Code:0x{code:02X} */ {{')
        for b0, b1 in cell_rows:
            lines.append(f'    0x{b0:02X}, 0x{b1:02X},')
        lines.append('  },')  # trailing comma OK in C99

    lines.append('};')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Written: {out_path}")


def debug_preview(glyphs, codes):
    """Print Scale2x result for selected character codes."""
    for code in codes:
        src_grid = glyph_to_grid(glyphs[code])
        dst_grid = scale2x(src_grid)
        print(f"\n--- 0x{code:02X} ('{chr(code) if 0x20 <= code <= 0x7E else '?'}') ---")
        print("Source 5x7:")
        print(visualise(src_grid, SRC_W, SRC_H))
        print("Scale2x 10x14:")
        print(visualise(dst_grid, DST_W, DST_H))


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_dir = os.path.dirname(script_dir)
    src_path = os.path.join(repo_dir, 'lib', 'st7735', 'fontk_8x8.h')
    out_path = os.path.join(repo_dir, 'lib', 'st7735', 'font_12x16_ank.h')

    if not os.path.exists(src_path):
        print(f"Error: {src_path} not found", file=sys.stderr)
        sys.exit(1)

    print(f"Reading: {src_path}")
    glyphs = parse_fontk_8x8(src_path)
    print(f"Parsed {len(glyphs)} glyphs")

    # Preview a few characters
    preview_codes = [0x41, 0x61, 0x30, 0xB1, 0xC6]  # A, a, 0, ｱ(half-kana), ｦ
    debug_preview(glyphs, preview_codes)

    generate_header(glyphs, out_path)
    print("\nDone.")


if __name__ == '__main__':
    main()
